In [3]:
import numpy as np

## Esercizio 1

Creare un array 1d del tipo [0,1,0,1,0,1,0,1,0,1,0...]

In [2]:
n = 1000000

In [43]:
#%%timeit    #FUNZIONE MAGICA -> calcolo il tempo della cella
#numpy
array_1d = np.zeros(n, dtype = np.int8)      #array di interi
array_1d[::2] = 1      #[0:n:2]
array_1d

array([1, 0, 1, 0, 1, 0, 1, 0], dtype=int8)

In [44]:
#%%timeit
#python
l = [i%2 for i in range(0,n)]
l

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1]

## Esercizio 2

matrice con zeri e uni che si alternano

In [25]:
n = 8
m = 8

In [38]:
array_2d = np.zeros((n,m), np.int8)
array_2d

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [39]:
array_2d[::2,::2] = 1
#array_2d[::1,1::2] = 1

In [40]:
array_2d

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [41]:
array_2d[::1,2::1]=1

In [42]:
array_2d

array([[1, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1]], dtype=int8)