In [1]:
import numpy as np

BROADCAST: combinare gli array  mediante operazioni matematiche, funziona sempre a patto che le dimensioni dell'array siano compatibili.

In [4]:
array1 = np.array([1, 2, 3, 4, 5])
array1 * 2

array([ 2,  4,  6,  8, 10])

In [7]:
np.exp(array1)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [9]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [11]:
array1 + 10

array([11, 12, 13, 14, 15])

In [13]:
array2 = np.array([-1, -2, -3, -4, -5])
array2

array([-1, -2, -3, -4, -5])

In [20]:
array1 + array2     #somma elemento per elemento, DIMENSIONE ARRAY UGUALE ALTRIMENTI NON FUNZIONA

array([0, 0, 0, 0, 0])

In [21]:
array1 * array2

array([ -1,  -4,  -9, -16, -25])

In [32]:
matrice1 = np.ones((5, 5))    
matrice2 = np.random.uniform(0,1,(5, 5))

In [33]:
#solo se dimensione uguale
matrice1 * matrice2

array([[0.90241439, 0.10163525, 0.55409943, 0.81103231, 0.38698022],
       [0.9184647 , 0.0941332 , 0.34733329, 0.35111695, 0.39737128],
       [0.00932311, 0.18638205, 0.24254987, 0.54356677, 0.64388681],
       [0.60662062, 0.67588038, 0.23258985, 0.29278684, 0.54165191],
       [0.16342679, 0.10256256, 0.67208364, 0.05698554, 0.64751383]])

In [34]:
matrice1 = np.ones((5, 5))    
matrice2 = np.random.uniform(0,1,(5, 1))

In [36]:
matrice1 + matrice2     #somma colonna per colonna

array([[1.52634856, 1.52634856, 1.52634856, 1.52634856, 1.52634856],
       [1.61444432, 1.61444432, 1.61444432, 1.61444432, 1.61444432],
       [1.42710719, 1.42710719, 1.42710719, 1.42710719, 1.42710719],
       [1.61997709, 1.61997709, 1.61997709, 1.61997709, 1.61997709],
       [1.58013044, 1.58013044, 1.58013044, 1.58013044, 1.58013044]])

In [38]:
matrice_5 = np.ones((5,5)) + 4
matrice_5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])