# Verifica su Python e introduzione a Numpy
### BESSONE ELISA

In [9]:
import numpy as np

## ESERCIZIO 1
Il file *robots.txt* contiene un frammento del vero file *robots.txt* di un importante quotidiano online. Tutte le righe che iniziano con la parola chiave `Disallow:` contengono le URL di pagine del quotidiano alle quali i software automatici di web crawling o di indicizzazione non dovrebbero mai accedere. La prima directory della URL indica la tipologia di notizia a cui punta l'URL. Per esempio la riga `Disallow: /economia/finanza-personale/2010/Prova-Metadati_a1b5a008-f178-11df-8c4b-00144f02aabc.shtml`fa riferimento a una notizia di **economia**.

Crea un programma in Python 3 che legga il file e generi un dizionario in cui:
* la chiave è la tipologia di notizia,
* il valore è il numero di notizie di quella tipologia.

In [40]:
dizionario_notizie = {}

In [41]:
f = open('robots.txt', 'r')
testo = f.readlines()
f.close()

In [42]:
righe = []
for i in range(len(testo)):
    righe.append(testo[i+1].replace("Disallow: /", " ").lower().split("/"))
    
    print(righe[i][0])
    print(len(righe))    

 politica
1
 esteri
2
 cronache
3
 cronache
4
 politica
5
 cronache
6
 sport
7
 economia
8
 scienze_e_tecnologie
9
 economia
10
 spettacoli
11
 primo_piano
12
 primo_piano
13
 ioscrivo
14
 primo_piano
15
 notizie-ultima-ora
16
 economia
17
 primo_piano
18
 cultura
19
 cronache
20
 gallery
21
 cronache
22
 cronache
23
 primo_piano
24
 primo_piano
25
 cronache
26
 cronache
27
 cronache
28
 notizie-ultima-ora
29
 primo_piano
30
 primo_piano
31
 primo_piano
32
 politica
33
 politica
34
 politica
35
 politica
36
 politica
37
 politica
38
 cronache
39
 cronache
40
 cronache
41
 cronache
42
 primo_piano
43
 primo_piano
44
 primo_piano
45
 cronache
46
 cronache
47
 primo_piano
48
 primo_piano
49
 economia
50
 primo_piano
51
 primo_piano
52
 cronache
53
 primo_piano
54
 cronache
55
 primo_piano
56
 primo_piano
57
 primo_piano
58
 cronache
59
 primo_piano
60
 cronache
61
 notizie-ultima-ora
62
 primo_piano
63
 primo_piano
64
 economia
65
 cronache
66
 politica
67
 cronache
68
 cultura
69
 notizi

IndexError: list index out of range

In [43]:
riga = []
for i in range(len(righe)):
    riga.append(righe[i][0])
    if riga[i] not in dizionario_notizie:
        dizionario_notizie[riga[i]] = 1
    else:
        dizionario_notizie[riga[i]] += 1

In [44]:
dizionario_notizie

{' politica': 17,
 ' esteri': 1,
 ' cronache': 34,
 ' sport': 1,
 ' economia': 6,
 ' scienze_e_tecnologie': 1,
 ' spettacoli': 2,
 ' primo_piano': 45,
 ' ioscrivo': 1,
 ' notizie-ultima-ora': 7,
 ' cultura': 3,
 ' gallery': 1,
 ' sette': 1,
 ' inchieste': 1}

## ESERCIZIO 2
Crea un array di numpy che contenga tutti i numeri interi tra 2 e 1000 (estremi inclusi), ma nel quale tutti i numeri divisibili per 7 sono sostituiti da uno 0. Infine crea un array contenente tutti i numeri interi tra 2 e 1000 (estremi inclusi) ma privo di tutti i numeri divisibili per 7.

for i in range(len(righe)):
    if righe[i][0] not in dizionario_notizie:
        dizionario_notizie[righe[i][0]] = 0
    else:
        dizionario_notizie[righe[i][0]] += 1

In [314]:
array = np.arange(2,1001)

In [313]:
for i in range(array.size):
    if array[i] % 7 == 0:
        array[i] = 0

In [96]:
array

array([   2,    3,    4,    5,    6,    0,    8,    9,   10,   11,   12,
         13,    0,   15,   16,   17,   18,   19,   20,    0,   22,   23,
         24,   25,   26,   27,    0,   29,   30,   31,   32,   33,   34,
          0,   36,   37,   38,   39,   40,   41,    0,   43,   44,   45,
         46,   47,   48,    0,   50,   51,   52,   53,   54,   55,    0,
         57,   58,   59,   60,   61,   62,    0,   64,   65,   66,   67,
         68,   69,    0,   71,   72,   73,   74,   75,   76,    0,   78,
         79,   80,   81,   82,   83,    0,   85,   86,   87,   88,   89,
         90,    0,   92,   93,   94,   95,   96,   97,    0,   99,  100,
        101,  102,  103,  104,    0,  106,  107,  108,  109,  110,  111,
          0,  113,  114,  115,  116,  117,  118,    0,  120,  121,  122,
        123,  124,  125,    0,  127,  128,  129,  130,  131,  132,    0,
        134,  135,  136,  137,  138,  139,    0,  141,  142,  143,  144,
        145,  146,    0,  148,  149,  150,  151,  1

In [103]:
nonZero = array!=0

In [104]:
array[nonZero]

array([   2,    3,    4,    5,    6,    8,    9,   10,   11,   12,   13,
         15,   16,   17,   18,   19,   20,   22,   23,   24,   25,   26,
         27,   29,   30,   31,   32,   33,   34,   36,   37,   38,   39,
         40,   41,   43,   44,   45,   46,   47,   48,   50,   51,   52,
         53,   54,   55,   57,   58,   59,   60,   61,   62,   64,   65,
         66,   67,   68,   69,   71,   72,   73,   74,   75,   76,   78,
         79,   80,   81,   82,   83,   85,   86,   87,   88,   89,   90,
         92,   93,   94,   95,   96,   97,   99,  100,  101,  102,  103,
        104,  106,  107,  108,  109,  110,  111,  113,  114,  115,  116,
        117,  118,  120,  121,  122,  123,  124,  125,  127,  128,  129,
        130,  131,  132,  134,  135,  136,  137,  138,  139,  141,  142,
        143,  144,  145,  146,  148,  149,  150,  151,  152,  153,  155,
        156,  157,  158,  159,  160,  162,  163,  164,  165,  166,  167,
        169,  170,  171,  172,  173,  174,  176,  1

## ESERCIZIO 3
Dato `n`numero intero dispari maggioreo uguale a 5 crea una matrice di numpy che abbia la struttura seguente esemplificata, per il caso `n=7`. 

`[[0.35012821 0.13462121 0.38492916 0.51293425 0.25255366 0.85166111 0.59550361]
 [0.47468085 0.         0.         1.         0.         0.         0.18300893]
 [0.23703845 0.         0.         1.         0.         0.         0.89905447]
 [0.52372585 1.         1.         1.         1.         1.         0.95780342]
 [0.51881137 0.         0.         1.         0.         0.         0.03430885]
 [0.09985312 0.         0.         1.         0.         0.         0.78938087]
 [0.37453082 0.21909742 0.6154127  0.89541758 0.79158936 0.68202705 0.82876577]`
 
La cornice della matrice deve essere composta di numeri pseudocasuali compresi tra 0 e 1, mentre l'interno deve essere riempito di 0 tranne nella riga e nella colonna mediane, le quali conterrano degli 1.
 

In [10]:
n = 5

In [11]:
matrice = np.random.uniform(0., 1., (n, n))

In [12]:
matrice

array([[0.61979067, 0.40169381, 0.1412861 , 0.70629033, 0.30325721],
       [0.07427592, 0.2975637 , 0.44778816, 0.27037341, 0.27465177],
       [0.24184918, 0.21406136, 0.28516057, 0.89472405, 0.77454065],
       [0.81672392, 0.20778546, 0.41523597, 0.19406497, 0.76965112],
       [0.40586596, 0.55562795, 0.68435399, 0.08396457, 0.53295955]])

In [13]:
for i in range (1,n-1):
    matrice[i:n-1,i:n-1] = 0
    matrice[n//2, i] = 1
    matrice[i, n//2] = 1

In [14]:
matrice

array([[0.61979067, 0.40169381, 0.1412861 , 0.70629033, 0.30325721],
       [0.07427592, 0.        , 1.        , 0.        , 0.27465177],
       [0.24184918, 1.        , 1.        , 1.        , 0.77454065],
       [0.81672392, 0.        , 1.        , 0.        , 0.76965112],
       [0.40586596, 0.55562795, 0.68435399, 0.08396457, 0.53295955]])