In [1]:
import numpy as np

In [8]:
lista = [1, 2, 3, 4]

In [9]:
type(lista)

list

In [10]:
array = np.array(lista)

In [11]:
array

array([1, 2, 3, 4])

In [12]:
type(array)

numpy.ndarray

In [13]:
3 * array

array([ 3,  6,  9, 12])

In [14]:
3 * lista

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
10 + array

array([11, 12, 13, 14])

In [16]:
array

array([1, 2, 3, 4])

In [17]:
a = array.copy()      #copio array in un altro
a

array([1, 2, 3, 4])

In [62]:
b = np.array(lista[::-1])         #inverse gli elementi

In [19]:
a + b          #somma elemento per elemento dei due array, BROADCAST --> solo se hanno la stessa lunghezza.

array([5, 5, 5, 5])

In [20]:
zeri = np.zeros(10, np.int8)

In [21]:
zeri

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [22]:
uni = np.ones(10)
uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [2]:
np.random.uniform(1,2, 10)   #10 numeri compresi tra 1 e 2

array([1.49500966, 1.84209448, 1.22800671, 1.6752464 , 1.86522183,
       1.38177696, 1.8897466 , 1.92450499, 1.28991193, 1.78470334])

In [24]:
np.random.uniform(size=10)   

array([0.32762823, 0.96183326, 0.79153294, 0.93331971, 0.80197551,
       0.0237212 , 0.51766299, 0.65780876, 0.4098935 , 0.3229928 ])

In [25]:
np.random.randint(1,7,10)

array([5, 2, 6, 1, 5, 3, 6, 6, 3, 6])

In [34]:
alice = np.random.randint(1,7,10)     #array di numpy

In [31]:
bob = np.random.randint(1,7,10)

In [41]:
print(f"Lanci di Alice: {alice}")
print(f"Lanci di Bob: {bob}")

Lanci di Alice: [3 6 6 5 3 6 2 6 2 5]
Lanci di Bob: [1 3 1 2 5 1 3 6 6 5]


In [42]:
alice.dtype

dtype('int32')

In [43]:
alice_vince = alice > bob  
alice_vince

array([ True,  True,  True,  True, False,  True, False, False, False,
       False])

indicizzare con dei booleani --> INDICIZZAZIONE BOOLEANA

In [44]:
alice_vince.dtype

dtype('bool')

In [47]:
alice[alice_vince]     #punteggio di Alice quando ha visto 

array([3, 6, 6, 5, 6])

In [48]:
bob[alice_vince]          #punteggio di Bob quando Alice ha vinto

array([1, 3, 1, 2, 1])

In [51]:
np.arange(3, 20, 3)     #arriva da 3 a 20 (escluso) a passi di 3

array([ 3,  6,  9, 12, 15, 18])

In [52]:
np.arange(20)    #da 0 a 20 senza includere il 20

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
np.linspace(0.0, 5.0, 20)       #numero di partenza, numero di arrivo, quanti numeri tra quell'intervallo voglio. suddivide 
                                #l'array in n parti. 

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [59]:
np.random.uniform(0.,10.)         #numero casuale da 0 a 10

0.07667794771703651

In [5]:
np.random.uniform(0,10, size=5)         #array di size con all'interno numeri compreso tra 0 e 10

array([6.72466682, 0.43927041, 5.87071808, 8.28873218, 2.17025788])

In [67]:
np.random.choice(["Testa", "Croce"], 20)      #passo lista o array, posso indicare il numero di "scelte"  con ugual probabilità

array(['Croce', 'Croce', 'Testa', 'Testa', 'Testa', 'Croce', 'Testa',
       'Testa', 'Testa', 'Testa', 'Croce', 'Testa', 'Croce', 'Testa',
       'Croce', 'Croce', 'Testa', 'Croce', 'Testa', 'Testa'], dtype='<U5')

In [71]:
np.random.choice(["Testa", "Croce"], 10, p=[0.7, 0.3])  #simulare una MONETA TRUCCATA, indico la probabilità dei singoli eventi.

array(['Testa', 'Testa', 'Testa', 'Croce', 'Testa', 'Testa', 'Croce',
       'Testa', 'Testa', 'Testa'], dtype='<U5')

In [74]:
np.random.normal(1., 1., 10)   #10 numeri estratti con una probabilità GAUSSIANA con media 1 e deviazione 2

array([ 0.53681707,  1.5374128 ,  2.94027193,  1.64289878,  0.60130672,
       -0.36002914,  1.97500583, -0.14033289,  0.96449444,  2.01080758])

In [3]:
altezze = np.random.normal(178, 10, 20)
altezze

array([182.62559472, 203.44884753, 190.76322934, 181.79216202,
       173.38107392, 171.2540843 , 187.27631503, 173.28708864,
       189.83810366, 183.71654371, 181.38463229, 195.33322672,
       168.85112155, 179.75117157, 175.93673245, 183.32689471,
       197.5509617 , 166.18080511, 167.7952346 , 198.96909007])

In [5]:
np.max(altezze)

203.44884752898403

In [6]:
np.min(altezze)

166.18080511102906

In [9]:
altezze_tupla = np.random.normal(178,10, (5,7))         #TUPLA a 2 dimensioni
altezze_tupla

array([[174.62800599, 172.50628867, 169.83069583, 181.96495434,
        182.49719349, 178.84860429, 174.63084108],
       [195.11822962, 187.84310284, 183.83401555, 161.16812912,
        179.29865114, 173.09135975, 184.43331076],
       [193.88508393, 183.35961747, 189.23127469, 166.35323426,
        177.28591045, 182.63417983, 184.20102441],
       [168.11369029, 194.13868904, 179.15584591, 182.52265157,
        182.12873424, 172.05811324, 191.51732635],
       [170.50727935, 181.19202521, 184.80900397, 174.94669578,
        172.89730976, 181.46502375, 182.30022705]])

### Array a due dimensioni unidirezionali

-se metto il punto dopo un valore imposto a FLOAT

In [25]:
array_2d = np.array([[1., 2., 3.],[4., 5., 6.,]])
array_2d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
array_2d.shape    #shape array, tupla che ha tanti elementi quanti ha la dimensione dell'array

(2, 3)

In [27]:
array_2d.dtype

dtype('float64')

In [21]:
array_2d_casuale = np.random.uniform(0., 1., (8, 2))
array_2d_casuale

array([[0.17876327, 0.43515817],
       [0.64576188, 0.29866239],
       [0.47562676, 0.19080606],
       [0.41379739, 0.94040766],
       [0.40610326, 0.66548102],
       [0.00610201, 0.6331093 ],
       [0.93432859, 0.99116257],
       [0.75468433, 0.05786528]])

In [22]:
array_2d_casuale.shape

(8, 2)

### Stampo un solo elemento in posizione x, y

In [42]:
array_2d_casuale[7,0]      

0.7546843338039133

### Stampo una colonna

In [43]:
array_2d_casuale[:,0]      

array([0.17876327, 0.64576188, 0.47562676, 0.41379739, 0.40610326,
       0.00610201, 0.93432859, 0.75468433])

### Stampo una riga

In [44]:
array_2d_casuale[4, :]

array([0.40610326, 0.66548102])

### Blocco: stampa la porzione di array che voglio. 

Posso usare lo SLICING

In [47]:
array_2d_casuale[2:5, :]     #5 escluso

array([[0.47562676, 0.19080606],
       [0.41379739, 0.94040766],
       [0.40610326, 0.66548102]])

### Assegnazione

In [49]:
array_2d_casuale[2:5, :] = 1
array_2d_casuale

array([[0.17876327, 0.43515817],
       [0.64576188, 0.29866239],
       [1.        , 1.        ],
       [1.        , 1.        ],
       [1.        , 1.        ],
       [0.00610201, 0.6331093 ],
       [0.93432859, 0.99116257],
       [0.75468433, 0.05786528]])

### Indicizzazione booleana 

lavoro con una condizione sugli elementi

In [4]:
array_1d = np.arange(0,5)

In [5]:
resto_fa_zero = array_1d % 2 == 0

In [6]:
array_1d[resto_fa_zero]

array([0, 2, 4])

In [9]:
array_1d[resto_fa_zero] = 999
array_1d

array([999,   1, 999,   3, 999])

### Indicizzazione con array di indici o fancy-indexing

In [11]:
array_1d = np.random.uniform(0., 1., 10)
array_1d

array([0.07956004, 0.7096852 , 0.63948228, 0.95071024, 0.04746698,
       0.40296918, 0.95771615, 0.65275048, 0.36883607, 0.77665112])

In [14]:
array_1d[np.array([1, 2, 9])]

array([0.7096852 , 0.63948228, 0.77665112])

In [16]:
array_1d[np.array([1, 2, 9])] = 999
array_1d

array([7.95600364e-02, 9.99000000e+02, 9.99000000e+02, 9.50710243e-01,
       4.74669777e-02, 4.02969183e-01, 9.57716154e-01, 6.52750475e-01,
       3.68836067e-01, 9.99000000e+02])